# This is a basic workflow

name: Android Build

on: 
  # triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Action tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "build"
   lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the code
        uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: Run Lint
        run: ./gradlew lintDebug

      # Runs a multi-line script
      - name: Upload html test report
        uses: actions/upload-artifact@v1
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

    unit-test:
      needs: [lint]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v1

        - name: Run tests
          run: ./gradlew test

        - name: Upload test report
          uses: actions/upload-artifact@v1
          with:
            name: unit_test_report
            path: app/build/reports/tests/testDebugUnitTest/

